# String. Required. PostgreSQL URI in the format postgresql://username:password@host:port
#url=postgresql://tmail:secret1@postgres:5432
url=postgresql://${env:POSTGRES_USER:-secret1}:${env:POSTGRES_PASSWORD:-secret1}@${env:POSTGRES_HOST:-postgres}:${env:POSTGRES_PORT:-5432}

# String. Optional, default to 'postgres'. Database name.
database.name=${env:POSTGRES_DB:-postgres}

# String. Optional, default to 'public'. Database schema.
database.schema=${env:POSTGRES_SCHEMA:-public}

# Boolean. Optional, default to false. Whether to enable row level security.
row.level.security.enabled=false
